version: '3'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_APP_API_BASE_URL=http://backend:3000/api
    depends_on:
      - backend

  backend:
    image: your-backend-image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=logplatform
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 