name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Tests
      run: npm run test:unit
      
    - name: Build
      run: npm run build
      
    - name: Build and Push Docker Image
      run: |
        docker build -t log-platform:${{ github.sha }} .
        docker tag log-platform:${{ github.sha }} ${{ secrets.DOCKER_REGISTRY }}/log-platform:${{ github.sha }}
        docker push ${{ secrets.DOCKER_REGISTRY }}/log-platform:${{ github.sha }} 